name: tiny-diffusion
channels:
  - defaults
  - conda-forge
dependencies:
  # Python version
  - python=3.11
  # Hugging Face libraries and pytorch
  - pip
  - pip:
      - diffusers[torch]==0.34.0
      - transformers==4.55.3
      - accelerate==0.23.0
      - safetensors==0.5.3
      - torch==2.6.0+cu118
      - torchvision==0.21.0+cu118
      - --extra-index-url https://download.pytorch.org/whl/cu118
  # ONNX & TensorRT
  - pip:
      - onnx==1.18.0
      - onnxruntime-gpu==1.22.0
      - tensorrt==10.13.0.35
  # Quantization
  - pip:
      - brevitas==0.12.1
  # Utilities
  - numpy
  - pandas
  - matplotlib
  - pillow
  - tqdm
  - scikit-learn
  - jupyterlab
  - pre-commit=4.2.0
  - types-PyYAML=6.0.12.20250809
